@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class CommandBox
Class ResultDisplay
Class ResolveWindow
Class LeftRightDisplay
Class ExerciseListPanel
Class RegimeListPanel
Class ScheduleListPanel
Class SuggestionListPanel
Class ExerciseCard
Class RegimeCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow

MainWindow *--> HelpWindow
MainWindow *--> CommandBox
MainWindow *--> ResultDisplay
MainWindow *--> ResolveWindow
MainWindow *--> ExerciseListPanel
MainWindow *--> RegimeListPanel
MainWindow *--> ScheduleListPanel
MainWindow *--> SuggestionListPanel

ExerciseListPanel --> ExerciseCard
RegimeListPanel --> RegimeCard

MainWindow --|> UiPart

HelpWindow --|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
ResolveWindow --|> UiPart
LeftRightDisplay --|> UiPart
ExerciseListPanel --|> UiPart
ExerciseCard --|> UiPart
RegimeListPanel --|> UiPart
RegimeCard --|> UiPart
ScheduleListPanel --|> UiPart
SuggestionListPanel --|> UiPart

ExerciseCard .right.> Model
UiManager -right-> Logic
MainWindow -right-> Logic

ResolveWindow -> LeftRightDisplay

ExerciseListPanel -[hidden]left- HiddenLogic
ExerciseCard -[hidden]left- HiddenLogic
HelpWindow -[hidden]- CommandBox
MainWindow -[hidden]-|> UiPart
@enduml
